# Generated by Django 2.1.3 on 2019-03-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('classify_level', models.IntegerField(blank=True, null=True)),
                ('delete_flag', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='kefan', max_length=36, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, default='kefan', max_length=36, null=True)),
                ('order_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shop_classify',
                'managed': False,
            },
        ),
    ]
